### ISSUE TITLE
Set up a test project and NuGet Install the package and verify it can connect to the Sandbox NotifyNL Api

### ISSUE THREAD

**Issue by frankmolenaar1986** [Worth-NL/notifications-net-client#3]

**Comment by Thomas-M-Krystyan** [comment]
DONE
- The "project" is set up (console app)
- NuGet is installed (easy peasy, all dependencies resolved, everything is compiling)

IN PROGRESS
- "connecting to our own sandbox API service"

**Comment by Thomas-M-Krystyan** [comment]
![image](https://github.com/Worth-NL/notifications-net-client/assets/22969536/306d9a8a-01be-4f47-adc6-a60ebf2f613d)

PS: We need to use a valid API authorization token (aka. "apiKey")
